export const FRIENDS_GET_SUCCESS = "FRIENDS_GET_SUCCESS"
export const MESSAGE_GET_SUCCESS = "MESSAGE_GET_SUCCESS"
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS"
export const IMAGE_MESSAGE_SEND = "IMAGE_MESSAGE_SEND"